### ISSUE TITLE
UI for cycle dates

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2810] opened 2019-01-09 15:11 UTC
New from Excella Meeting

**Comment by Piglady64** [comment] 2019-01-09 15:13
4 replies
Katrina Wagner [6 minutes ago]
oh didn't realize we didn't have that...thought it was being done in a ticke.t  Did you do it behind the scenes and I need to create another ticket to add UI?  The intent is they will be adding them themselves


Brice Corum (CSM, CSD) [3 minutes ago]
Community admins for cyclical type communities have the ability to add cycles, but once added there is no way to view it or edit it.


Brice Corum (CSM, CSD) [3 minutes ago]
They would see the cycles when they attempt to create an opportunity


Katrina Wagner [< 1 minute ago]
Got it - they can add now but not review and edit

**Comment by bmcorum** [comment] 2019-02-12 17:32
Duplicate of #2835

**Closed by bmcorum** 2019-02-12 17:32 UTC
Labels: State Dept.
