### ISSUE TITLE
Splash page for production

### ISSUE THREAD

**Issue by mtorres253** [openopps/openopps-platform#1469] opened 2016-09-23 16:51 UTC
- [x] Build splash page with approved copy - needs copy
- [ ] Backup all data (including images)
- [x] New branch - public folder with HTML/CSS file
- [ ] Delete app from production space
- [ ] Turn off all services from production space

When ready:
- [ ] point https://openopps.18f.gov/

**Comment by acolter** [comment] 2016-09-23 17:05
@LisaLNelson Please review the following copy and edit as you see fit. 

On October 1, Open Opportunities will be temporarily shutting down while the platform finds a new home. Until now, Open Opportunities has been operated by 18F and owned by the Office of Products and Platforms, both within the General Services Administration. We’re in the process of transferring operations of Open Opportunities to a new team, but because of compliance regulations we must pause use of the platform until then. 

We apologize for this interruption in the amazing work all of you are doing with Open Opportunities. All of the data and current opportunities are saved. We hope to find a new team to operate the platform soon, and then we will be able to restore all existing opportunities. 

Thank you for your patience during this transition, and for working to build a passionate community working to grow the government’s impact.

**Comment by LisaLNelson** [comment] 2016-09-23 17:40
Got it and I will think on it.

**Comment by rogeruiz** [comment] 2016-09-28 17:50
The splash page branch is here
https://github.com/openopps/openopps-platform/tree/static-splash-page/

The preview URL is here
https://openopps-splash-page.18f.gov/

**Comment by rogeruiz** [comment] 2016-09-30 23:09
While the above came out of this, and some more reproducible steps for great @18F projects, we thankfully won't be putting up a splash page today so I'll close this.

**Closed by rogeruiz** 2016-09-30 23:09 UTC
Labels: P1 High priority
