### ISSUE TITLE
Department of State: Application : Statement of Interest 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2488] opened 2018-08-23 03:10 UTC
User Story: 

This ticket will take the student to the Statement of Interest Page of the application Process. 

Acceptance Criteria:
•	Once a student starts typing, the information will auto save. 
•	A save alert will appear. 
•	Clicking the X will make the save alert disappear. 
•	Clicking the back button will take the student back to the Language and Skills Section. 
•	Clicking Save and Continue will take the Student to the Review Application Page. 

Invision Mock:
https://opm.invisionapp.com/d/main#/console/15360465/319289352/preview

**Comment by bmcorum** [comment] 2018-08-23 11:56
@tlorrison, @mchung07, and @Lforeman22 I am not thrilled about the "auto save" in the acceptance criteria. Can we please look at another alternative? Auto saving just because the text changed could potentially lead to excessive networking traffic between the user's browser and Cloud.gov servers as well as excessive database traffic with continual save. Could we just add a "Save Changes" button instead?

**Comment by Piglady64** [comment] 2018-11-09 21:09
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35514&fullScreen=false&_a=edit

**Comment by kbwagner** [comment] 2019-01-24 15:38
duplicate of 2881 - closing

**Closed by kbwagner** 2019-01-24 15:38 UTC
Labels: Apply Process, Requirements Ready, State Dept.
