### ISSUE TITLE
As a task creator, validation errors should be more obvious when saving a draft

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1077] opened 2015-10-17 19:02 UTC
I added a task for a customer who is on her way to Australia.  After adding the task I was not able to change the requester name from my name to hers  and save it. In addition, I tried to make a few other changes to the task and they would not save.

**Comment by ultrasaurus** [comment] 2015-10-18 21:42
It appears that the problem is that the task title was too long -- did we recently add validations for that? @dhcole  

![image](https://cloud.githubusercontent.com/assets/41906/10566833/73e94ca8-75a6-11e5-9977-5dee9898e45d.png)

**Comment by ultrasaurus** [comment] 2015-10-18 21:53
@GailSwanson @jeremiak what do you think of either scrolling up to where the errors is, or adding some red text near the save button that says that there were validation errors?

**Comment by dhcole** [comment] 2015-10-19 15:35
It doesn't look like there is any validation on the API / model. @jeremiak is this new on the front end or just copied over from the old task creation modal?

**Comment by jeremiak** [comment] 2015-10-20 19:26
This is carried over from the old task creation model, which relies on putting some of the validation criteria as data attributes in the right fields.

Totally open to changing it, or at the very least making it obvious where the errors are.

**Comment by GailSwanson** [comment] 2015-10-20 20:11
It's always good to have error states visible from the current view. There are a number of ways to handle that gracefully. One option is to scroll the page so that the error and message are in view. Another is to put a generic message next to the submit button alerting the user to look for the errors above. The best way to deal with it is realtime error checking so that as soon as the user enters data that will throw an error into a field, you display the error message on the field. That way they fix it before moving on.

**Comment by kbwagner** [comment] 2018-03-20 22:43
Closing - duplicate of 1859

**Closed by kbwagner** 2018-03-20 22:43 UTC
