### ISSUE TITLE
As an administrator I need to be able to add people to opportunities.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1913] opened 2018-03-09 16:09 UTC
There are times when individuals need my help to add their name as an interested party to an opportunity.  There needs to be a way for me to do that. (As an FYI that was available in the old system.)

**Comment by bmcorum** [comment] 2018-03-09 17:11
@LisaLNelson I would like to do some user research to see if now that we have address some older issues and improved the process of applying to see if users are still having issues applying for opportunities.

**Comment by LisaLNelson** [comment] 2018-03-09 20:50
@bmcorum It came up today.  I needed to add someone.

**Comment by bmcorum** [comment] 2018-03-15 13:50
Duplicate of #1878

**Closed by bmcorum** 2018-03-15 13:50 UTC
Labels: Approved, Design
