### ISSUE TITLE
Department of State  - Not Eligible- Citizenship

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2638] opened 2018-10-30 20:28 UTC
Who:  Student Applicant
What: Alert explaining why they are not eligible.
Why: Applicants should not be allowed to complete the application process if they do not meet the citizenship requirement

A/C

- If an applicant has indicated in their profile that they are not a U.S. citizen they will see the alert
-The alert will be presented as soon as the applicant clicks the "apply" button
 If they applicant has indicated in their profile that they are not a U.S. citizen they will  not be able to proceed with their application. 

Visual Mock- https://opm.invisionapp.com/share/ZEPNZR09Q54#/333432320_State_-_Not_Eligible_-_Citizenship

![image](https://user-images.githubusercontent.com/15252970/50783074-c9f20380-1277-11e9-8e9b-87046fc898a9.png)

**Comment by Piglady64** [comment] 2018-11-09 19:18
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35504&fullScreen=false&_a=edit

**Comment by kbwagner** [comment] 2019-01-24 15:35
duplicate of 2877 - closing

**Closed by kbwagner** 2019-01-24 15:35 UTC
Labels: Apply Process, Katrina/Review, State Dept.
