### ISSUE TITLE
As a task creator or PO I would like to be able to differentiate between a participants skills and interests.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1561] opened 2017-10-11 17:18 UTC
In the user profile skills and interests are lumped together making it difficult to tell which is which.

![screen shot 2017-10-11 at 1 17 24 pm](https://user-images.githubusercontent.com/9039852/31455756-9fe0ab2e-ae86-11e7-893b-a8eeebe6bbaa.png)

Separating the skills and interests make the data more useful. As an example we could separate the boxes as below:

Skills
Lean start-up, crowdsourcing, marketing, collaboration, building partnerships

Interests:
coding and programming, data analysis

From 1712: 
As an open opps users, my skills and interests in my profile should be displayed in separate boxes in the completed profile; presently they display in a single, combined box.

example of present display in my open opps profile: 

![image](https://user-images.githubusercontent.com/25315047/36054938-203f4a4c-0dc7-11e8-8b49-28291dc12faf.png)

**Comment by bmcorum** [comment] 2017-10-13 11:44
Looks like skills are tags of type "skill" and interest are tags of type "topic" so this should be easy enough to filter in backbone to display separately.

**Comment by kbwagner** [comment] 2018-03-29 17:59
likely done with the FAI design.  Check after release 2.

**Comment by kbwagner** [comment] 2018-05-31 18:30
5/31/18 - closing as duplicate of 2246

**Closed by kbwagner** 2018-05-31 18:30 UTC
Labels: Enhancement, Skills & Interests, UI/visual
