### ISSUE TITLE
As a user, when I create my profile I have to refresh to see uploaded image.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1545] opened 2017-09-12 18:09 UTC
When I upload an image, I can't see it until I refresh the page.

Steps to reproduce:
2. Click on your name, then "Profile"
3. Click "Edit Profile" link on the top right corner
4. Click the camera to upload a photo
5. Watch the network requests
6. Choose a photo
7. Note the progress bar display, but the photo is not displayed
8. Note the network request shows the photo is uploaded and retrieved, yet it is not displayed (perhaps something is wrong with the api?)
9. Manually refresh the page (Cmd + R)
10. Note only the small profile image on top of the right corner is changed
11. Manually refresh the page again (Cmd + R)
12. Note the big profile picture is changed

**Comment by kbwagner** [comment] 2018-04-09 20:45
Duplicate of 1852.  Merging 1625, 1627, 1545 into 1852

**Closed by kbwagner** 2018-04-09 20:45 UTC
Labels: Profile
