### ISSUE TITLE
Create new account from Find Profile

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2476] opened 2018-08-16 14:58 UTC
User Story: As an Open Opportunities new user, I want to be able to create a new account if I don't already have one.  

Acceptance Criteria: 
- On the find my profile page, we need the ability to create a new acccount
- under the cancel button have "Don't have an Open Opportunities account?"
- There will be a Create a new account button
- Clicking on this button will take the user to their profile to fill in the required information.

Invision Mock: https://opm.invisionapp.com/d/main#/console/14696610/313413542/preview

**Comment by bmcorum** [comment] 2018-08-29 11:49
On hold until we can get additional profile information from USAJOBS.

**Comment by Piglady64** [comment] 2018-11-09 21:46
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35520&fullScreen=false&_a=edit

**Comment by bmcorum** [comment] 2018-11-19 14:20
Duplicate of #2401

**Closed by bmcorum** 2018-11-19 14:20 UTC
Labels: Approved, Hold, Requirements Ready, Sign In, State Dept.
