### ISSUE TITLE
Browser Tabs

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#1762] opened 2018-02-23 19:34 UTC
I logged in as the participant and opened a different tab to log in as the admin, and the new tab went directly to being open as the participant.  Ok, but when I logged out as that user in one tab and proceeded to log in as the agency admin, the other tab changed to the agency admin without me doing anything.  I thought that I did something funny so I closed both (edge) and opened chrome, and it did the same thing, except I had to refresh the page for it to change, and it still had the other person’s information up as I was on the profile page to begin with.

Steps to recreate in UAT:
•	Logged into open opps as agency admin
•	Opened another browser tab				Tab opened as the agency admin from the other tab
•	Logged out as agency admin in tab two
•	Logged in as participant	in tab 2				in IE tab automatically changed tab 1 to participant.  In chrome I had to refresh tab1 to have it change to participant

**Comment by ultrasaurus** [comment] 2018-02-26 05:55
This is working as expected.  To log into the web app with two different users, you start a browser window that doesn't have any user info:
- "incognito" window in Chrome
- InPrivate browsing in Internet Explorr
- Private browsing in Firefox

https://www.digitalcitizen.life/how-browse-web-incognito-all-big-browsers

**Comment by bmcorum** [comment] 2018-02-26 12:31
@Kibrahacha67, this is functioning as intended. Your browser can only establish a single session regardless of how many tabs you may have open. However if you were to open a different browser or open a browser in "private" mode you would be able to establish multiple sessions.

**Comment by kbwagner** [comment] 2018-03-20 17:28
Closing.  Works as designed.

**Closed by kbwagner** 2018-03-20 17:28 UTC
Labels: Bug
