### ISSUE TITLE
Create Unpaid Internship Opportunity: Add languages

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#2627] opened 2018-10-22 19:29 UTC
User Story: As an Unpaid internship Opportunity Creator, I want to be able to add languages that I would like for my intern to have to the opportunity in order to be able to match applicants effectively.

Acceptance Criteria:
When the opportunity creator selects "Add language" from Step 2 of the unpaid internship create opportunity page, the following occurs:
- They are taken to a new page titled "Foreign languages"
- "All fields are required" displays
- The language selector displays
- Speaking language skill level - radio buttons for None, Novice, Intermediate, Advanced
- Writing language skill level - radio buttons for None, Novice, Intermediate, Advanced
- Reading language skill level - radio buttons for None, Novice, Intermediate, Advanced
- Help link for "What does novice, intermediate, advanced mean?"  Links to https://www.usajobs.gov/Help/how-to/account/profile/languages/
- Cancel and return -Does not save language input and returns creator to the Create Opportunity page
- Save language - returns the creator to the create page where the language is displayed

https://opm.invisionapp.com/share/UHNZS9XEYR8#/319310102_Create_-_Unpaid_-_Add_Language_-Desktop-

Related Tickets:
2624 - Select community for opportunity
2625 - Create opportunity
2627 - Create opportunity - Languages
2665 - Add languages display
2628 - Preview opportunity

**Comment by kbwagner** [comment] 2018-10-22 19:42
Design Questions: @abudz19 @humancompanion 
1) Does "Read language skill level" make sense"?  Or should it be "Reading"?  Probably fine but I had to look at it a couple of times.
2) once a language has been added, there are two "add language" buttons in the design.  Is that purposeful?

**Comment by abudz19** [comment] 2018-10-25 13:56
1. Read makes sense, though it is a little awkward. We could change it to "Speaking skill level, Writing skill level, Reading skill level" for a better flow and to align to the ILR Language Skill Level Descriptions used by FSI.

2.  Yeah that looks like a mistake, there are two sections. After you add one language, the top "Language Requirements" section with button should probably be removed. 

Matt? @humancompanion

**Comment by humancompanion** [comment] 2018-10-25 13:59
Agree with item 1 though that likely came from Core so if we fix it in OO
we should also fix it in Core for consistency.

For item 2 there should only be one section. We’ll find x the mock soon.

**Comment by abudz19** [comment] 2018-10-26 13:58
@kbwagner I've received Dan's approval for the text change (1). When Tracy has confirmed, we can update the ticket and then let one of the Titan BA's know so they can add a ticket to their backlog to keep it consistent in Core.

**Comment by Piglady64** [comment] 2018-11-09 19:46
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35507&fullScreen=false&_a=edit

**Comment by kbwagner** [comment] 2018-12-12 22:47
Please make title "Foreign languages"

**Comment by kbwagner** [comment] 2018-12-13 16:18
@raywilliams - all updates are in the AC.

**Comment by jhanson12** [comment] 2018-12-19 18:19
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment] 2018-12-19 18:32
12/19/18 - Mdumas - testing....

**Comment by margaretdumas** [comment] 2018-12-20 14:06
12/20/18 - Mdumas - Moving back to development
- Languages are not loading
- Skill levels - radio buttons for selection does not display
- AC calls for "Federal languages" but "Foreign languages is displayed
- No tab focus in Edge for "When" field for creating the opportunity

**Comment by jhanson12** [comment] 2018-12-21 14:20
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment] 2018-12-21 15:02
12-21-18 LHammond in testing

**Comment by Kibrahacha67** [comment] 2018-12-27 17:47
@kbwagner - Hi Katrina, hope your holiday was great, the title of this page in the AC says "Federal Languages" but the Page is labeled "Foreign Languages" can you either confirm the AC or update?  I'm confused and talked to Tani and she stated that someone told her Foreign Languages...Thank you.

**Comment by kbwagner** [comment] 2018-12-27 18:45
@Kibrahacha67 yes sorry that was a typo - it should always be "Foreign".  AC updated

**Comment by Kibrahacha67** [comment] 2018-12-27 18:54
@kbwagner :) Thanks

**Comment by Kibrahacha67** [comment] 2018-12-28 15:30
12-28-18 LHammond Testing completed. moving to review.

**Comment by kbwagner** [comment] 2019-01-03 15:43
1/3/19 - When I add a language and go back to add another, the radio buttons default to the levels I selected on my first language.  The radio buttons should always be "none" when I add a new language.
- moving back to Dev.

Checking with Debbie LeNard on the URL for the help since it is a profile help and doesn't make much sense here. But passes AC.

**Comment by raywilliams** [comment] 2019-01-03 15:46
@kbwagner  I checked in a change this morning for #2665 with the same issue. The change corrects the behavior so that the language skill levels reset to None as they should.

**Comment by kbwagner** [comment] 2019-01-03 15:56
@raywilliams Question as I'm testing create internship...when I click Save Language, it takes me back to the top of the Create Internship page and I have to scroll back down.  Is it possible to take the focus back to where they were on the page at the Foreign language section?

**Comment by kbwagner** [comment] 2019-01-03 15:58
1/3/19 - confirmed with Debbie that the help link is correct and will be updated prior to State deployment.

**Comment by raywilliams** [comment] 2019-01-03 16:01
@kbwagner That might be something we can do. I'll try it now.

**Comment by bmcorum** [comment] 2019-01-08 18:23
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment] 2019-01-08 18:34
1/8/18 - Mdumas ....testing

**Comment by margaretdumas** [comment] 2019-01-08 19:08
Mdumas - I can add the same language as many times as I like.  Is this a data issue in the TEST environment ?

**Comment by bmcorum** [comment] 2019-01-09 13:35
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment] 2019-01-09 14:31
01/9/19 - Mdumas - testing....

**Comment by margaretdumas** [comment] 2019-01-09 14:40
Mdumas - Passed testing , on to review.

**Comment by kbwagner** [comment] 2019-01-10 14:06
1/10/19 - KWagner tested in Chrome.
Ready for final review.

**Closed** 2019-02-19 18:37 UTC
Labels: Approved, Opportunity Create, Requirements Ready, State Dept.
