### ISSUE TITLE
As a GSA employee, I would like to see GSA Opportunities on a page that feels like a "place"

### ISSUE THREAD

**Issue by ultrasaurus** [openopps/openopps-platform#1299] opened 2016-04-22 12:38 UTC
As a General Services Administration (GSA) employee, I would like a page that can be shared that will take people to a “GSA Only” page that lists just all GSA opportunities (part time and full time) so I don’t have to search all opportunities in order to find just the GSA ones, and I feel like this is a GSA place. As the program administrator for the Office of Human Resource Management (OHRM), this will enable us to send out program announcements and easily point employees to the GSA-specific opportunities.

This page would not require login (so technically people at other agencies would be able to see it if a link were shared, but they wouldn't typically be presented with this page).

This page would have a specific URL that OHRM could send out to GSA employees that would take participants to GSA only rotation program only (maybe including GSA part-time projects too, maybe promote federal-wide in some way)

**Comment by ultrasaurus** [comment] 2016-04-22 15:54
Here are some mocks from design ideation sessions with @vz3 and @brendansudol 

1 - "Streamlined Header"
![image](https://cloud.githubusercontent.com/assets/41906/14747058/50f70f88-0867-11e6-8be0-09912b40b31b.png)

2 - "Branded Sidebar"
![image](https://cloud.githubusercontent.com/assets/41906/14747118/8c0379d6-0867-11e6-8c53-41198e176905.png)

3 - "Create Opportunity Highlight"
![image](https://cloud.githubusercontent.com/assets/41906/14747142/a46b7122-0867-11e6-97fc-bcc14a46aaa7.png)

**Comment by ultrasaurus** [comment] 2016-07-28 16:18
Note: upon review by GSA OHRM team, they liked "2 - Branded Sidebar" option best, feeling it was cleaner and they liked the way the gray background helped the opportunities to stand out

**Comment by mtorres253** [comment] 2016-08-02 23:11
This seems like a duplicate of #1271

**Closed** 2017-09-12 17:12 UTC
Labels: duplicate, Full Time Details, icebox
