### ISSUE TITLE
Department of State: Update Application After Submit

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2885] opened 2019-01-22 19:57 UTC
Who: Student Applicant
What: The ability to update an application after it has been submitted
Why: As a student applicant, I want to be able to re-order or delete and add a new internship opportunity as well as make changes to information in my application after I submit.

A/C
- When a student applicant returns to Open Opportunities after submitting their application the "apply" button on the the internship opportunity will read "update application" in the box in the right rail.
- When the user clicks the "update application" button they will be sent to the "select opportunities" page in the application process"
   - The user will be able to "delete" an internship opportunity from their list
   - The user will be able to re-order their internship opportunities in their list
   - The user will be able to add a new internship opportunity (opportunities) to their list after deleting one or more from their list
   - The user will be able to navigate to other pages and make changes as necessary

Mock: 
https://opm.invisionapp.com/d/main#/console/16373614/342347596/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Piglady64** [comment] 2019-01-22 19:59
Who: Student
What: Ability to make changes to my application after I have submitted.
Why:As a student I may want to change my selections or the order of my selections.

**Comment by bmcorum** [comment] 2019-02-21 18:33
Duplicate of #2912

**Closed by bmcorum** 2019-02-21 18:33 UTC
Labels: Apply Process, Approved, Requirements Ready, State Dept.
