### ISSUE TITLE
Need to replace the Mandrill email notification system currently sent from the Platform.

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1542] opened 2017-09-08 13:24 UTC
Implement the Amazon Web Services (AWS) email tool. Specifically:

Reconfigure the system email variable URL prefix – change from digital.gov to OpenOpps@usajobs.gov. The System name variable will continue to be "Open Opportunities"
Update cloud "from" variable to be a non response email address to be provided.

Related Tickets:
1567 - Apply branding to emails
1583 - update email content

GSA is planning to block Mandrill so we ned to find another solution to replace the email notifications we currently.

**Comment by lawrencek76** [comment] 2017-09-08 13:43
### Some Options:
1. [Mailgun](https://www.mailgun.com/pricing) Free 10000 messages / month
2. [SendGrid](https://sendgrid.com/pricing/) Free 100 messages / day
3. [Mandril](http://www.mandrill.com/pricing/) No free (Why is GSA moving away from it? maybe because it was just bought by mailchimp.)
4.  Others (AWS?) etc
5. Cloud.gov provided option (won't be in time for service cut off)

### Questions
If we sigin up for one of these who "owns" it and pays the bills if any?
How many messages are we sending per day today?
Are any approvals needed or do we "just do it"(TM)?

### Observations
We should go with Mailgun simply because they have the coolest name.

**Comment by LisaLNelson** [comment] 2017-09-08 13:59
Yes, Mailchimp is not on the GSA IT approved paid software list so that is probably what happened.

**Comment by LisaLNelson** [comment] 2017-09-12 17:08
As an FYI Here is info on setting up notifications https://github.com/openopps/openopps-platform/wiki/Notifications

**Comment by brodydittemore** [comment] 2017-09-14 16:56
Creating a spike (#1548 for further conversation). Let's use this issue for the feature replacement.

**Comment by LisaLNelson** [comment] 2017-10-04 20:39
GSA has extended the deadline until the end of December. Cloud.gov may have an alternative by then.

**Comment by kbwagner** [comment] 2018-03-21 00:57
1542 was a duplicate of this ticket but may contain additional informaiton

**Comment by bmcorum** [comment] 2018-03-28 13:59
We have successfully converted to and deployed the use of AWS SES as a replacement for Mandrill, and it is effective in production as of Wednesday March 28th 2018.

**Closed** 2018-03-28 14:00 UTC
Labels: Spike
