### ISSUE TITLE
Save Internship: Should be removed when the application cycle closes

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3234] opened 2019-03-20 23:13 UTC
Who: Internship applicants
What: Saved internship view
Why: To keep my saved view up to date

Acceptance criteria:
- A saved internship should be removed when the application cycle closes.

**Comment by bmcorum** [comment] 2019-03-21 14:02
@kbwagner since saved internships show in a list on the select program page of the application it might be confusing to students to see it in that list but then when clicking "Go to Saved" on their profile the saved then does not show. Does USAJOBS hide my saved JOAs once I apply to them? This could also be confusing on the internship view page as well. Would the save star on the page still show as saved or not since I now submitted my application but it no longer shows in my landing page.

**Comment by kbwagner** [comment] 2019-03-21 14:07
@bmcorum Yes - USAJOBS will remove a saved JOA once you have applied so it no longer shows on your saved board.  I'll check and see if it also undoes your star.

**Comment by kbwagner** [comment] 2019-03-21 18:57
@bmcorum confirmed in USAJOBS
- Once I applied, the job was removed from my saved landing page
- The star is now marked as open/not selected
One note -after I have applied and the star is now unselected...I can actually reselect it to save...it shows up on my saved...and then I select apply, it updates my application and falls off again.  Don't need to replicate that just saying.

**Comment by Piglady64** [comment] 2019-04-17 14:59
Julie changed the A/C after discussing this with Brice and Tracy on 4/16/19. The saved internship will be removed after the application cycle has closed. Now that the student can come back in and update their application we don't want them to delete it and then decide they did want to select it and have to go back through all of the internships to find it again.

**Comment by bmcorum** [comment] 2019-04-18 13:59
Duplicate of #3241

**Closed by bmcorum** 2019-04-18 13:59 UTC
Labels: Approved, Landing page, Requirements Ready, State Dept.
