### ISSUE TITLE
As a task creator, I need to be able to see errors when I submit for review

### ISSUE THREAD

**Issue by LisaLNelson** [openopps/openopps-platform#1314] opened 2016-05-11 19:08 UTC
There seems to be an error in the system. A task was created and when the TC tried to move it from draft to submitted he got an error message.  I went into the opportunity and clicked on the submit button a number of times and it did not submit it. The button turned a darker blue but it never changed the state.

![screen shot 2016-05-11 at 3 10 00 pm](https://cloud.githubusercontent.com/assets/9039852/15193161/7ba771d2-178a-11e6-90c2-561a6ca4b0e0.png)

I tried creating a new opportunity and was able to save as a draft and submit. I received an email confirming.

This [specific draft task](https://openopps.digitalgov.gov/tasks/506/edit) can't be submitted, but others can be.  No errors on the JavaScript console.

**Comment by ultrasaurus** [comment] 2016-05-13 15:51
the issue is that the error has scrolled out of view:
![image](https://cloud.githubusercontent.com/assets/41906/15253606/de366f52-18e7-11e6-8285-fd24f5565609.png)

We should really display the error near the Submit button as well as where it is currently displayed.

**Comment by kbwagner** [comment] 2018-04-09 19:42
Duplicate of 1859.  Closing and merging details.

**Closed by kbwagner** 2018-04-09 19:42 UTC
Labels: Opportunity Create
