### ISSUE TITLE
Department of State: Experience questions

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2920] opened 2019-01-24 22:01 UTC
Who: Student intern applicant
What: experience questions
Why: to gather additional information about the applicant's experience 

Acceptance Criteria:
On the Experiences & References page, under the experience section, There will be 3 questions with Yes and No radio buttons
Do you have any overseas experience?
If the user selects "Yes"  they will presented with the following:
Please indicate what type of overseas experience you possess.
Student
Dependent
Peace Corps
Military
Government
Other

the user will be able to make multiple selections by checking the boxes

If the user selects "Other" they will be presented with two text boxes
"If you chose "Other", please specify"
Please indicate the total length of your overseas experience(s)

Do you have, or have you had, a Security Clearance?
If the user selects "Yes" they will be presented with two text boxes
Type of security clearance
Please provide who issued the clearance

Have you previously participated in the Virtual Student Federal Service (VSFS) program?

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Kibrahacha67** [comment] 2019-02-13 16:52
@Piglady64 - the invision mock above takes me to the home page, is that correct?  Seems like it should go to Experience questions in profile...

**Comment by Piglady64** [comment] 2019-02-13 17:04
@Kibrahacha67 I used the public link for this because someone down there didn't have an InVision account. The public link takes you to the beginning of the project.

Here is the link directly to the page if you have an account: https://opm.invisionapp.com/d/main/#/console/15360465/319289315/preview

**Comment by Kibrahacha67** [comment] 2019-02-13 17:06
Disregard second question I get it now...

**Comment by bmcorum** [comment] 2019-03-05 19:02
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment] 2019-03-05 21:35
03/5/19 - Mdumas - in testing...

**Comment by margaretdumas** [comment] 2019-03-06 21:21
03/6/19 - Mdumas - passed AC.  Moving on to review.

**Comment by Piglady64** [comment] 2019-03-11 13:09
3/11/19 When I select the "Present" button when adding new experience I am getting the following error. Returning to development. 
![image](https://user-images.githubusercontent.com/15252970/54126210-6b631600-43dd-11e9-8be4-b36973a47d0f.png)

**Comment by bmcorum** [comment] 2019-03-12 17:27
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment] 2019-03-12 17:41
3-12-19 LHammond in testing

**Comment by bmcorum** [comment] 2019-03-13 15:09
@Kibrahacha67, @margaretdumas, @Piglady64 

The issue identified by @Piglady64 would be a failure of ticket #2878 which covers the functionality and requirement for saving or editing experience data. Unless there are other findings related to AC outlined in this ticket I would think this ticket is "good to go".

**Comment by Kibrahacha67** [comment] 2019-03-13 15:15
Moving this back to review as the issue is associated with ticket 2878 which is in development.

**Comment by Piglady64** [comment] 2019-03-15 19:56
3/15/19 Reviewed and moved to Final Approval

**Closed** 2019-05-01 20:26 UTC
Labels: Apply Process, Approved, Requirements Ready, State Dept.
