### ISSUE TITLE
Department of State: Application: Select Program

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2484] opened 2018-08-23 01:58 UTC
Who: Student
What: Select Programs Page
Why: The student needs to apply to 3 internships. They will do that from this page

This ticket will bring you to the first step in the application process for a department of state internship.

Acceptance Criteria:
• When a  student clicks continue from "Next Steps" page they will be brought to the “Select Programs” page. 
• The first choice they applied to will show in the 1st choice card. 
• Clicking delete will give them a confirmation alert (follow design) system. 
• Clicking on the confirmation will delete their 1st choice.
• Clicking on the 2nd choice card will bring them back to the search page. 
• Clicking on the 3rd choice box will bring them back to the search page. 
• Once all 3 choices are selected the save and continue button will appear.
• Clicking the save and continue button will take you to the Experience & References Page of the Application Process. 

Invision:

**Comment by kbwagner** [comment] 2019-01-24 16:17
duplicate of 2785 - closing

**Closed by kbwagner** 2019-01-24 16:17 UTC
Labels: Apply Process, State Dept.
