### ISSUE TITLE
Ability for Community Managers to update Office/Post information - Add new

### ISSUE THREAD

**Issue by tlorrison** [openopps/openopps-platform#3851] opened 2019-08-21 21:04 UTC
Who: State community managers
What: Ability to add/remove Bureau/Office/post
Why: in order for them to self maintain their constantly changing organization structure

Acceptance Criteria:
As a community manager, I need the ability to update office/post information as it changes per cycle through the UI of Open Opportunities.
- State (unpaid) Community managers and sitewide administrators will have access to update the bureau/office/post information
- Navigation: Administration --> Community --> Department of State Student Internship Program (unpaid) --> Manage community
- At the bottom of the existing page add a section called "Bureau and Office/Post Information"
- There will be an "+ Add new" button
- There will be a grid that displays all of the Bureaus in bold with associated Office/post underneath.
- Each bureau and office/post will have an Edit and Delete icon to the right. Alt Tags should display for Edit and Delete
https://opm.invisionapp.com/share/U8R4CAV3HXF#/388169636_Open_Opps_-_Add_Office_Or_Bureau_V4

**Add New:**
- Selecting "+Add new" will display a pop up modal https://opm.invisionapp.com/share/U8R4CAV3HXF#/382345164_Open_Opps_-_Add_Office_Or_Bureau_-_With_Modal_Copy
- The modal title will be "Add new bureau or office/post"
- There will be a section for "Select bureau or office/post" with a radio button for Bureau and a radio button for Office/post
- If Bureau is selected, the text, "Enter the name of the bureau you want to add." will be displayed. The maximum field length for the field will match the existing and a character counter will display.
- If Office/post is selected, the page will display as follows: 
https://opm.invisionapp.com/share/U8R4CAV3HXF#/382345163_Open_Opps_-_Add_Office_Or_Bureau_-_With_Modal_Copy_2
Select the bureau that the office or post belongs to with a dropdown selector of existing bureaus
Enter the name of the office or post you want to add.
A free form text box will be displayed to enter the office/post.  the max field size will the same as the existing max field size and a character counter will display
- All fields are required
- There will be a Cancel and an Add button
- Cancel will close the modal and not save any changes
- Add will add the new Bureau/Office/Post
- - If add is selected, the user will return to the manage page and receive a confirmation: https://opm.invisionapp.com/d/main#/console/17049184/390904889/preview  
"Office/post added" and "You have successfully added [bureau or office/post name] to you community
or "Bureau added" and "You have successfully added the [bureau name] to your community
- If a Bureau or Office/post is duplicative of an existing Bureau or office/post, notify the user that this already exists.  When checking for duplication, case should not matter.
- Tracking data should track who added, what was added, and the date/time.

Mocks: https://opm.invisionapp.com/d/main#/projects/prototypes/17049184

Related tickets:
3851 - add new
4065 - Edit
4066 - Delete

**Comment by abudz19** [comment] 2019-08-21 21:41
@tlorrison Is this a design request or a platform ticket?

**Comment by tlorrison** [comment] 2019-08-21 21:46
I think we may need some design support to think about where we’ll put the functionality and how it will work. This ticket may not be picked up this sprint, so we should have 2 weeks to figure it out.

**Comment by kbwagner** [comment] 2019-09-10 20:44
@abudz19 I added one comment.  Let's chat when you get back.  Invision is being weird and taking me all over the place but I think I get the gist.  The modals are fine.

**Comment by dalenard21** [comment] 2019-09-11 18:13
@abudz19 @kbwagner I added more comments. I'm a bit confused about how this will all work since there's a relationship between the bureaus and offices/posts. I'd like to sit with one of you and go through it.

**Comment by kbwagner** [comment] 2019-09-11 19:03
Yep I messaged Alex something similar.  She's out for another week so we can chat again when she's back.

**Comment by abudz19** [comment] 2019-10-17 16:32
@kbwagner looks good.

**Comment by dalenard21** [comment] 2019-10-18 15:57
@abudz19 and @kbwagner sorry I have one more content edit.  I'd like to change the phrase:

"This action cannot be undone."
to
"You can't undo this action."

This will keep consistent with active voice and the recommendation I made for the "Confirm delete cycle" messaging in issue https://github.com/openopps/openopps-platform/issues/2458

 

Thanks.

**Comment by bmcorum** [comment] 2019-10-18 16:01
@dalenard21 I believe the reason we say "This action cannot be undone" vs "You cannot undo this action" is to make the user aware this is an action that truly cannot be reversed. If I read a statement that reads "You cannot undo this action" I infer that someone else possibly with elevated permissions or roles can reverse my action.

**Comment by dalenard21** [comment] 2019-10-18 17:45
@bmcorum @abudz19 @kbwagner 

1. I updated the content to not include "You can't undo this action.", because really, they could go back and enter the bureau or office/post again.  

2. If the user is trying to delete a bureau, we might want to say "Are you sure you want to delete [insert bureau name]? If you delete the bureau, you will also delete all of its offices and posts."

3.  @bmcorum brought up the idea of adding a message telling the user how many internships/users are currently using the bureau or office that they want to delete.  Having this information might help the user think twice about 'removing' a bureau or office/post.  Thoughts?

**Comment by kbwagner** [comment] 2019-10-29 14:11
@tanichacko @Kibrahacha67 I know there was some confusion on these tickets.  Alex has wired the mock and I confirmed the mock and AC match. The only thing I added was AC on a confirmation screen

**Comment by tanichacko** [comment] 2019-11-06 15:38
bureau added screenshot
![bureau added.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/ab162edd-fedb-46f0-98be-857d8b1742c8)
bureau added data info
![bureau data added.png](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/3038e897-d96c-4a88-a916-66ffcb90c10f)

 Office added screen shot
![office added.PNG](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/3d3b397f-327f-460e-be64-f126370c3a37)
office added data Info
![office added data.png](https://images.zenhubusercontent.com/5b86ec29172d9f4986242cc3/df9734a4-2f52-43b2-a485-08dd5a900d02)

**Comment by jhanson12** [comment] 2019-11-06 15:45
@Kibrahacha67 and @margaretdumas  this is ready for testing.

**Comment by Kibrahacha67** [comment] 2019-11-06 16:17
11-06-19 LHammond in testing

**Comment by jhanson12** [comment] 2019-11-07 19:57
@Kibrahacha67 and @margaretdumas this is ready for testing.

**Comment by Kibrahacha67** [comment] 2019-11-07 20:34
11-07-19 LHammond in testing
testing completed moving to review.

**Comment by kbwagner** [comment] 2019-11-13 21:06
11/13/19 - KWagner tested in Chrome/Test
Will chat with Debbie about some possible enhancements for confirmation messages

**Closed** 2019-12-20 19:35 UTC
Labels: Admin, Approved, Community, Requirements Ready, State Dept.
