### ISSUE TITLE
Department of State: Application: Experience and Reference Page 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2485] opened 2018-08-23 02:20 UTC
Who: Student Applicant
What: Experience and Reference information
Why: As a student applicant I need to add my experience to my application and provide references.

Acceptance Criteria:

-  When a student is on this page the first circle with the number 1, will turn green. 
-  The information on this page will be populated with the information provide in the users USAJOBS   profile
-  There will be a header titled "Expereince & References"
-  Each experience will be listed separately with the following information:
   -  The title of the experience 
   - There will be a blue + next the title of the experience which will expand the information 
   -  The name of the Agency will be in bold
   -  The date range 
   -  Clicking on the Name of the Experience link will expand the card.
   - Clicking on the Reference name link will expand the card. 
   - Clicking add Experience, will bring the student to the Experience page. From this page, clicking “save will bring the student back to the experience and reference page. 
- There will be 3 questions with Yes and No raido buttons
   - Do you have any overseas experience?
   - Do you have, or have you had, a Security Clearance?
   - Have you previously participated in the Virtual Student Federal Service (VSFS) program?
- There will be a header titled "Reference (optional)
  - Each reference will have the following information on the card:
    - A blue + that will expand the card when the user clicks
    - The name of the reference which will expand the card when clicked
    - The name of the agency or company bolded in black
- Clicking add References, will bring the student to the References page. From this page, clicking save will bring the student back to the experience and references page. 
- Adding additional information to the experience of reference page, will not add the additional information to the students USAJOBS profile. 
- Clicking the back button will take the student back to the Select Programs Page. 
- Clicking Save and Continue will take the student the Education and Transcript Page. 

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289315/preview

**Comment by kbwagner** [comment] 2019-01-24 15:30
Closing - duplicate of 2878

**Closed by kbwagner** 2019-01-24 15:30 UTC
Labels: Apply Process, Katrina/Review, State Dept.
