### ISSUE TITLE
Department of State: Select internship opportunities from Saved Search

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2862] opened 2019-01-16 21:24 UTC
Who: Student
What: Selecting an opportunity from "Saved Searches"
Why: As a student, I would like to be able to select my internship opportunities from a list of opportunities I have previously saved.

A/C
- When the user selects an internship opportunity from the list in the "saved internship opportunities" box it will be displayed in the next available choice (1st, 2nd or 3rd).  
- There will be a "Go to saved" button on the right bar that will take the user to to the user's landing page where they can view all of their saved searches
- All of the saved searches that have not been selected as one of the 3 choices in the right bar will say "select"
- Once the user has moved a saved search into their application (one of their 3 choices)  on the left the saved search will say "Selected"
- The total number of saved searches will display at the top of the right rail. 

InVision Mock: https://opm.invisionapp.com/d/main/#/console/15360465/319289308/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

Related ticket 2788

**Comment by bmcorum** [comment] 2019-02-12 16:43
Need an anchor for my saved internships on landing page

**Comment by Kibrahacha67** [comment] 2019-03-26 18:55
@Piglady64 - I have a question, is this to be from the saved searches on the right rail of the second page of the application or from the landing page Saved?  or both?  I need to understand how many test cases are needed.

**Comment by Piglady64** [comment] 2019-03-26 20:54
the user should be able to select an internship from the list on the right rail which is visible on the "select internships" page
![image](https://user-images.githubusercontent.com/15252970/55032522-6a3e0580-4fe7-11e9-8d40-1788dbbaed37.png)
Because we haven't started developing the "saved" part yet so we can't test that right now. This is only for the right rail. I anticipate another ticket for moving saved searches into the empty slots from the "Saved" section of their landing page.

**Comment by bmcorum** [comment] 2019-04-01 14:15
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment] 2019-04-02 11:50
4-2-19 LHammond in testing
-first selected internship, showed as selected in the right rail, however once the 2nd choice was selected from the right rail, the "Selected" changed back to "Select".  The other two choices continued to stay "Selected".  Moving back to development.

**Comment by jhanson12** [comment] 2019-04-02 18:07
Unable to reproduce issue.

**Comment by Kibrahacha67** [comment] 2019-04-02 18:16
4-2-19 LHammond Testing completed moving to review.

**Comment by Piglady64** [comment] 2019-04-19 16:28
4-19-19 - Julie reviewed- moving to final approval

**Closed** 2019-05-01 18:45 UTC
Labels: Apply Process, Approved, Requirements Ready, State Dept.
