### ISSUE TITLE
Image upload

### ISSUE THREAD

**Issue by Kibrahacha67** [openopps/openopps-platform#1627] opened 2018-01-05 18:54 UTC
Picture   upload to profile goes into perpetual upload mode (see image)  Pic uploaded but never got success from the   application.  Did open it in another   browser and pic was there.

**Comment by kbwagner** [comment] 2018-04-09 20:42
Duplicate of 1852 - merging and closing this one.

**Closed by kbwagner** 2018-04-09 20:42 UTC
Labels: Profile
