### ISSUE TITLE
Department of State:  Application: Language and Skills 

### ISSUE THREAD

**Issue by Lforeman22** [openopps/openopps-platform#2487] opened 2018-08-23 02:59 UTC
User Story:

This ticket will take the student to the Language and Skills Section of the Application Process. 

Acceptance Criteria:
•	If any language information has been in the students’ USAJOBS profile, it will show up in this section of the Application process. 
•	Clicking on the Language Name Links will fold out additional information in the card. 
•	Clicking on the Add Language link, will take them to another Languages and Skills Page. All fields in this section are required. 
•	Clicking “ What does novice, intermediate and advanced mean?, link will take the student to the help center. 
•	Clicking Cancel and return will not save any information and will bring the student back to the Language and Skills page that is part of the application process. 
•	Clicking Save Language, will save the information and bring the student to the Skills section. 
•	All sections on this page are required. 
•	Skills section is an autocomplete section. 
•	Clicking Cancel and Return will take the Student back to the Language and Skills part of the application process. 
•	Clicking save skills will take the student to the Language and Skills part of the application process. 
•	Clicking the Add Skills Button from the Language and Skills page in the application process will bring the student to the Add Skills page. 
•	Clicking the back button from the Language and Skills Page of the application process will take the student to the Education and Transcript Page. 
•	Clicking save and Continue from the Language and Skills page of the application process will take the Student to the Statement of Interest Section of the Application. 

Invision Mock:
https://opm.invisionapp.com/d/main#/console/15360465/319289343/preview
https://opm.invisionapp.com/d/main#/console/15360465/319289346/preview
https://opm.invisionapp.com/d/main#/console/15360465/319289349/preview

**Comment by Piglady64** [comment] 2018-11-09 21:12
Corresponding TFS Ticket: https://tfs.opm.gov/tfs/RecruitmentSystems/USAJOBS/_queries?id=35515&fullScreen=false&_a=edit

**Comment by kbwagner** [comment] 2019-01-24 15:33
Duplicate of 2880 - closing

**Closed by kbwagner** 2019-01-24 15:33 UTC
Labels: Apply Process, State Dept.
