### ISSUE TITLE
Updates to Submitted application page

### ISSUE THREAD

**Issue by kbwagner** [openopps/openopps-platform#3232] opened 2019-03-20 23:02 UTC
Who: Student
What: Update/Withdraw page
Why: As a student I would like the ability to update or withdraw my application and need an easy way to accomplish this

Acceptance Criteria:
- From the landing page Applied section, when the intern clicks on the link in the Program column, they will be taken to the Submitted application page where they see the Submitted application section
- The header reads, "Submitted application"
- The text under the header reads, "You have submitted the following application to the <community name> for <cycle name>.
- There will be two buttons: Update and Withdraw
- Update will be handled with ticket 3231
- Withdraw is handled with ticket 3087
- Under the update and withdraw buttons, the header reads, "Applying to these internship opportunities" <NOTE question for Alex on this title>
- Then their first, second, and third choices will display

Questions:
- Will they still get the update modal? 
  - Julie - They will get the modal if they click the "update" button. We need to make sure they understand they have to resubmit their application not just make edits. 
- Will they also go to this page when they click Update application from the internship?
- They would likely also go to this page if they click Apply from an internship they didn't select but are clicking apply on after they submitted their 3
- What about an in process application?  They would skip this page if they go back to complete correct?
  - Julie- I think they would skip this page because they are not updating an internship they are completing an application in process.

Invision Mock: https://opm.invisionapp.com/share/ZEPNZR09Q54#/352514657_State_-_View_Selections_-_Update_Or_Withdraw_-Desktop-

**Comment by bmcorum** [comment] 2019-04-16 18:53
This looks like a duplicate of #3087

**Comment by Piglady64** [comment] 2019-04-17 15:50
this is a duplicate - closing this ticket

**Closed by Piglady64** 2019-04-17 15:50 UTC
Labels: Apply Process, Requirements Ready, State Dept.
