### ISSUE TITLE
Sort by  option

### ISSUE THREAD

**Issue by JodieYoung1** [openopps/openopps-platform#1916] opened 2018-03-09 16:29 UTC
As a user, would like to sort the opportunity listing page by the following: date posted, estimated completion date, agency, etc.

Note: Add a sort by option on opportunity listing page (i.e. date posted, estimated completion date, agency, etc.) (multiple users suggested)

**Comment by kbwagner** [comment] 2018-04-05 20:32
Closing - duplicate of 2016

**Closed by kbwagner** 2018-04-05 20:32 UTC
Labels: Enhancement
