### ISSUE TITLE
Department of State - Progress Bar

### ISSUE THREAD

**Issue by Piglady64** [openopps/openopps-platform#2789] opened 2019-01-07 21:14 UTC
Who: Student Applicant
What: Progress bar in the Application process
Why: As a student applicant I want to see my progress and be able to see what else needs to be done

A/C
- There will be a progress bar at the top of each page (same design in USAJOBS application process)
- There will be 6 numbered steps
  - Select Internships 
  - Experience & References
  - Education & Transcripts
  - Languages & Skills
  - Statement of Interest
  - Review Application (this is not in the design)

- The circle will be a solid green once the applicant has completed that page
- The circle will be outlined in green when the applicant is on the page
- The circle will be outlined in white for pages the applicant hasn't completed yet

- A student must complete a page prior to moving forward to the next page.
- Once a page has been completed, however, they can navigate backward and forward to the page by clicking on the number.

InVision Link: https://opm.invisionapp.com/d/main/#/console/15360465/319289320/preview

Public Link: https://opm.invisionapp.com/share/ZEPNZR09Q54

**Comment by Piglady64** [comment] 2019-02-25 14:16
Added 6th step on progress bar for the "review" page. 
Updated Changes to moving back and forth (at the bottom of the A/C)
Added page specific InVision Link and Public link

**Comment by Piglady64** [comment] 2019-02-26 15:27
@raywilliams I wanted to make sure you saw the changes I made on this ticket yesterday (see comment above)

**Comment by raywilliams** [comment] 2019-02-26 15:31
@Piglady64  Yes, thank you. I just checked in changes to add the 6th step and the ability to navigate between steps.

**Comment by bmcorum** [comment] 2019-03-05 19:09
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by margaretdumas** [comment] 2019-03-05 20:59
@bmcorum @raywilliams I'm sending this one back because I don't see another ticket to use.  The progress bar works but if I go back and try to navigate with the Save and continue buttons on the page, that doesn't work.

**Comment by raywilliams** [comment] 2019-03-05 21:29
@margaretdumas this is sent back into testing after talking with you. The progress bar works but the Save and continue button on Step 1 does not, and it's still in development at the moment.

**Comment by margaretdumas** [comment] 2019-03-07 13:18
03/07/19 - Mdumas - In testing...

**Comment by margaretdumas** [comment] 2019-03-08 13:30
@Piglady64 . Please update AC to change "Foreign Languages & Skills" to reflect " Languages & Skills as in the mock if that is accurate.  This is what was designed.

**Comment by margaretdumas** [comment] 2019-03-08 13:38
@Piglady64  

If I go though all 6 steps then click step 1 or 2 of the progress bar, should all of the step after that go back to being white, while maintaining the changes? Or, is it ok for them to stay green?

![image](https://user-images.githubusercontent.com/19936109/54031697-7c155100-417d-11e9-8071-30ca59126fa1.png)

**Comment by Piglady64** [comment] 2019-03-08 14:47
@margaretdumas I changed "Foreign Languages & Skills" to "Languages & Skills" in the A/C. I know that DoS wanted the word "Foreign" in front of "Languages" for the create but we must have decided that it doesn't go in the "apply" as well. Good Catch

**Comment by margaretdumas** [comment] 2019-03-08 15:47
@Piglady64  What about the progress bar navigation question?

If I go though all 6 steps then click step 1 or 2 of the progress bar, should all of the step after that go back to being white, while maintaining the changes? Or, is it ok for them to stay green?

image

**Comment by Piglady64** [comment] 2019-03-08 16:10
@margaretdumas I checked in USAJOBS and if I go back to a previous step and make any changes everything after that goes back to white and the user has to save those pages again. I think we need to be consistent so the steps need to reset to white if the user goes back to any step and makes a change. The steps prior to the page they change remains green, they only have to review and save the steps after  the change. @bmcorum is this correct?

**Comment by bmcorum** [comment] 2019-03-12 17:31
@margaretdumas and @Kibrahacha67 this is ready for testing.

**Comment by Kibrahacha67** [comment] 2019-03-13 12:02
3-13-19 LHammond in testing

**Comment by Piglady64** [comment] 2019-03-15 19:45
3/15/19 Tested moving to final review

**Closed** 2019-05-01 20:25 UTC
Labels: Apply Process, Approved, Requirements Ready, State Dept.
